apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  # base64 credentials example
  adminUser: YWRtaW4tdXNlcg==
  adminPassword: bXktc2VjdXJlLXBhc3N3b3JkMTIz