apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-service-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: web-service
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http-web 
    path: /metrics
    interval: 15s
