---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: monitoring  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - name: web-service
        image: web-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-service-ingress
  namespace: monitoring
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: monitoring 
  labels:
    app: web-service
spec:
  type: ClusterIP
  selector:
    app: web-service
  ports:
  - name: http-web 
    protocol: TCP
    port: 80
    targetPort: 8000 
